---
- name: "get users HOME"
  getent:
    database: passwd
    key: "{{ ruby_user }}"
    split: ":"
  tags:
    - ruby

- name: "set ruby_user_home variable"
  set_fact:
    "ruby_user_home": "{{ getent_passwd[ruby_user][4] }}"
  tags:
    - ruby

- name: "install build depends"
  apt:
    pkg: "{{ item }}"
    state: present
    install_recommends: no
    update_cache: yes
    cache_valid_time: "{{ apt_cache_valid_time }}"
  with_items: "{{ ruby_software_dependencies }}"
  tags:
    - ruby

- name: "clone rbenv repository"
  git:
    repo: "https://github.com/rbenv/rbenv.git"
    dest: "{{ ruby_user_home }}/.rbenv"
    version: "{{ ruby_rbenv_version }}"
  become_user: "{{ ruby_user }}"
  tags:
    - ruby

- name: "create plugins directory"
  file:
    path: "{{ ruby_user_home }}/.rbenv/plugins"
    owner: "{{ ruby_user }}"
    group: "{{ ruby_group }}"
    mode: 0755
    state: directory
  tags:
    - ruby

- name: "clone ruby-build repository"
  git:
    repo: "https://github.com/rbenv/ruby-build.git"
    dest: "{{ ruby_user_home }}/.rbenv/plugins/ruby-build"
    version: "master"
  become_user: "{{ ruby_user }}"
  tags:
    - ruby

- name: "rbenv init"
  template:
    src: "rbenv.sh.j2"
    dest: "/etc/profile.d/rbenv.sh"
    owner: "root"
    group: "root"
    mode: 0755
  tags:
    - ruby

- name: "install ruby"
  shell: "/bin/bash -lc 'rbenv install {{ item }}'"
  args:
    creates: "{{ ruby_user_home }}/.rbenv/versions/{{ item }}/bin/ruby"
  become_user: "{{ ruby_user }}"
  with_items: "{{ ruby_versions }}"
  notify:
    - rbenv rehash
  tags:
    - ruby

- name: "set global ruby version"
  shell: "/bin/bash -lc 'rbenv global {{ ruby_global_version }}'"
  become_user: "{{ ruby_user }}"
  when: ruby_versions | length > 0
  notify:
    - rbenv rehash
  tags:
    - ruby

- name: "set gemrc"
  template:
    src: "gemrc.j2"
    dest: "{{ ruby_user_home }}/.gemrc"
    owner: "{{ ruby_user }}"
    group: "{{ ruby_group }}"
    mode: 0644
  tags:
    - ruby

- name: "install global gems"
  gem:
    name: "{{ item[1] }}"
    state: present
    executable: "{{ ruby_user_home }}/.rbenv/shims/gem"
    user_install: "no"
  environment:
    RBENV_VERSION: "{{ item[0] }}"
  become_user: "{{ ruby_user }}"
  with_nested:
    - "{{ ruby_versions }}"
    - "{{ ruby_global_gems }}"
  notify:
    - rbenv rehash
  tags:
    - ruby

- meta: flush_handlers
